### PR TITLE
Added toggle button to Wallet Section

### PR DESCRIPTION
**Pull request by darshannbs57**
##### Description
1. Added toggle button for Wallet Section
2. Lifting up state from child ( HeaderMenu ) to parent ( Wallet ) for getting collateral and trading balances
3. Added styles for buttons.
4. Added test case for Wallet component and move one test case from HeaderMenu to Wallet for getting balances on contract change

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
1. Wallet Section UI has new toggle button which can collapsed and expanded.
2. Test case for HeaderMenu is moved to Wallet component since getting balances is lifted up to 
Wallet section

##### Screenshots (Optional)
**Before Change**
befor_change

**After Change**
expanded
collapsed

##### Testing
**Test Path**
1. Navigate to Exchange Section
2. Wait till all balances are fetched for Wallet Section
3. Toggle Hide / Show Wallet button to see the new UI changes which collapses/expands on toggle.

##### Refers/Fixes
Fixes: #314

### CODE REVIEW

**Comment by darshannbs57** [comment]
@nitinrgupta I have already signed CLA but its not showing up here. Also I have resolved the merge conflict. Please review it now.

**Comment by nitinrgupta** [comment]
@darshannbs57 hmmm. That's weird. Could you resign or recheck the CLA status or something? Also please submit on Gitcoin so that you can get paid out :)

**Comment by nitinrgupta** [comment]
@darshannbs57 looks like there is some issue with Gitcoin! 
Please send your wallet address to @pelsasser so that you can get it paid out. 

@pelsasser @eswarasai any idea what's going on with the CLA?

**Comment by darshannbs57** [comment]
@pelsasser I'm facing issues with submitting my work so posting my wallet address  0x02B992EF6bcbB9bB38357197c8B3cFeF7ecE403c

**Comment by pelsasser** [comment]
@nitinrgupta - will merge this now, CLA is signed, I can confirm on the back end, not sure what is up with the check.

@darshannbs57 - I will get this paid out later today if your still unable to submit work.

**Comment by pelsasser** [comment]
@darshannbs57 - killed bounty and sent ETH your way. 

https://etherscan.io/tx/0xc831be2217c4ce65464bb8dcd9755db7108e6ba88f75f15a78aa47ca6619f6db

**Pull request merged**
