### PR TITLE
Preset quick deployment fields

### PR DESCRIPTION
**Pull request by perfectmak**
Enables setting quick deployment fields from url query params.

### CODE REVIEW

**Comment by eswarasai** [comment]
@perfectmak -- I see you're merging the upstream into your repository which creates unnecessary commits. Instead can you please do `git pull -r upstream master` and push them to your repository?

**Comment by perfectmak** [comment]
Yeah, I should do it that. Don't mind my lazy approach to merging upstream
😀.

**Comment by cryptomental** [comment]
This PR is so much needed!

http://localhost:3000/contract/deploy?mode=quick&contractName=ETHEUR&priceFloor=9000&priceCap=10000&priceDecimalPlaces=1&qtyMultiplier=1&oracleDataSource=URL&oracleQueryRepeatSeconds=60 is much much faster than copy-paste one by one.

We should add a few examples to readme on how this works.

**Comment by cryptomental** [comment]
I would just see in a few places cast to integer for integer fields e.g.:

```
name='priceFloor' initialValue={parseInt(initialValues.priceFloor)}
```

etc. as the autocompleted form complains that some values are non-int.

**Comment by perfectmak** [comment]
Thanks @cryptomental. I'll do that.

**Comment by cryptomental** [comment]
Great! I have seen webpack warnings about missing radix, so likely it needs to be explicitly added during cast.

**Comment by eswarasai** [comment]
@cryptomental -- Yes. For `parseInt`, `radix` is also needed to be specified. Ideally you should be seeing these errors in the IDE itself. Is it properly configured to use `.eslintrc`? Just curious to see if there's some issue with the linting rules

**Comment by perfectmak** [comment]
@cryptomental I've added the parse Integer values.

**Comment by cryptomental** [comment]
Looks good! Were you able to deploy a few contracts using quick deployer + MetaMask on the latest master branch? I tried Ganache instead of truffle and still out of gas... If that is confirmed the MarketContracOraclize contract ABI will need to be investigated in a detail to reduce gas consumed as much as possible. I am afraid that removing checks for sufficient funding may not be enough.

**Comment by pelsasser** [comment]
I was able to get this to work on a previous build of the protocol - recent
changes forced it over the edge.  Definitely some gas optimizations still
needed, but if we remove the recent additions we should be good here.

**Comment by cryptomental** [comment]
All right! I will revert then for the time being to the previous snaphot.

**Comment by pelsasser** [comment]
@cryptomental - struggle with some call back tests but will have a build out momentarily that I think will fix this

**Comment by pelsasser** [comment]
Fixed.

**Comment by cryptomental** [comment]
Ok, this can be merged now.

**Comment by pelsasser** [comment]
thanks guys for all the hard work!

**Pull request merged**
