### PR TITLE
fix header logo sizing to prevent truncation

### PR DESCRIPTION
**Pull request by Smona**
##### Description
This PR prevents logo truncation by updating media queries to rely on accurate absolute pixel widths. The design of the header could probably be further refined by keeping it at a single width and displaying only the most important items plus an overflow menu, but I've stayed within the scope of the issue.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
N/A

##### Testing
This is a simple CSS change, so I tested by opening in the latest Chrome, Firefox, and Safari.

##### Refers/Fixes
Fixes: #118

### CODE REVIEW

**Comment by eswarasai** [comment]
@Smona -- Having the height of `30px` for the MARKET Protocol Logo does resolve the issue but it makes the Navbar UI look weird. I'd recommend doing this:

- Increase the height of the MARKET Logo to `40px`
- Reduce the `padding-left` and `margin-right` to `20px`
- Change the padding of `ant-menu-submenu-title` to `0 10px`
- Reduce the `font-size` of `#nav` to `13px`

**Comment by Smona** [comment]
@eswarasai thank you for the suggestions! they were pretty spot on with some tweaking.

@pelsasser cool, this is my first bounty and i wasn't aware of that.

The new commit has the header and logo looking good at all widths 👍

**Comment by eswarasai** [comment]
@Smona -- This really looks perfect to me. Just one small change would be to reduce the font-size of the dropdown menu of `Deploy Contracts` for this class `.ant-menu-vertical .ant-menu-item` to `13px`. We can close this PR as soon as you can commit the change. Thanks :)

**Comment by pelsasser** [comment]
@Smona - glad you first bounty was with us! Thanks for the interest in the project.

**Pull request merged**
