### PR TITLE
Add support for React-Router Redirects

### PR DESCRIPTION
**Pull request by nemaniarjun**
Adds support to redirect any route to any route.
Also redirects /exchange/* to /exchange

Closes https://github.com/MARKETProtocol/dApp/issues/312

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

### CODE REVIEW

**Comment by nemaniarjun** [comment]
@eswarasai I know there are 2 PRs for the same issue. I and @nitinrgupta are both working on the issue together. 

The build on this one fails cause of the time error. Restarting this build will fix travis.

**Comment by nitinrgupta** [comment]
@nemaniarjun Are we? 🤔

**Comment by nemaniarjun** [comment]
@nitinrgupta I think you missed this comment on the issue: https://github.com/MARKETProtocol/dApp/issues/312#issuecomment-416222561

**Comment by nitinrgupta** [comment]
@nemaniarjun its @nithinr07 😉

**Comment by nemaniarjun** [comment]
@nitinrgupta Oh I am really really sorry, I just saw "Nitin" and didnt check the full username :sheep: :sweat_smile:

**Pull request closed without merging**
