### PR TITLE
ISSUE 78 with tests

### PR DESCRIPTION
**Pull request by maektwain**
##### Description

Validation on the smart contract : Valid smart contract address or not
##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes

Fixes: #78 
Fixes: #80

### CODE REVIEW

**Comment by maektwain** [comment]
@pelsasser and @eswarasai I think this works fine. 

Thanks

**Comment by maektwain** [comment]
I think it can be merged now.

**Comment by maektwain** [comment]
Done !

**Comment by maektwain** [comment]
@eswarasai So do I have to change the formatting or it can be merged.

**Comment by pelsasser** [comment]
I am going to merge this.  There is a still a missing check in `checkContract` to confirm the address is an ERC20 contract, not just a contract.  We can address that later in a different issue.

**Pull request merged**
