### PR TITLE
Price cap/floor graph

### PR DESCRIPTION
**Pull request by StevenJNPearce**
##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
I will think about tests for this tomorrow.

##### Screenshots (Optional) 
https://i.imgur.com/bjkVCsG.png

##### Refers/Fixes
Fixes: #241

### CODE REVIEW

**Comment by nitinrgupta** [comment]
Thanks for the quick turn around @StevenJNPearce! Let me know when this is ready for review.

**Comment by StevenJNPearce** [comment]
@nitinrgupta Ready for review. Tests are failing but i don't think it's related to my changes, was this branch was failing already?

**Comment by eswarasai** [comment]
@StevenJNPearce -- Indeed they are. The tests are failing on the base branch. So you don't need to worry about them. I'll let @nitinrgupta review and close this PR. Thanks for your time and efforts :)

**Comment by nitinrgupta** [comment]
@StevenJNPearce The branch is still in development. Need not worry about overall tests. We can tackle that later on.

**Comment by pelsasser** [comment]
this LGTM with the exception of flipping cap to be on the top.  @StevenJNPearce can you make those edits?

**Comment by StevenJNPearce** [comment]
Ok, I have flipped the cap and floor fields, resolved the merge conflict and rebased.

**Pull request merged**
