### PR TITLE
WIP: Fix Contract Dropdown

### PR DESCRIPTION
**Pull request by CosmicCoder96**
##### Checklist

- [x] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Affected core subsystem(s)

UI of contract Dropdown
##### Screenshots (Optional) 

image

##### Refers/Fixes

#334

### CODE REVIEW

**Comment by CosmicCoder96** [comment]
@nitinrgupta This effectively takes care of introducing, a search box and make the list scrollable instead of one big list like before. Also, I wanted to know how can the entries in the contract list be populated, currently there is just one contract in the list. So in order to test the Scroll functionality, I placed some dummy hardcoded entries while and the scrolling works fine.

**Comment by nitinrgupta** [comment]
@CosmicCoder96 thanks for the WIP PR. Yes, we flushed the contract list recently. Adding similar dummy data for you to test the scroll functionality should be fine. 

Also, I notice from the screenshot that it's not similar to what the UI specified in #334 looks like. I know its a WIP, but just putting it out there :)

**Comment by eswarasai** [comment]
@CosmicCoder96 -- Any update on this PR? Please do let us know once it's ready for review. Thanks!

**Comment by CosmicCoder96** [comment]
@nitinrgupta Can you take a look now, thanks - btw is it absolutely necessary to use a dropdown? Since select is specifically meant for this purpose.
--> Have adjusted height, width and placeholder text.
image

**Comment by nitinrgupta** [comment]
@CosmicCoder96 Will take a look. 

>  btw is it absolutely necessary to use a dropdown? 

I'm afraid so! It's because we have some future designs which are in line with the popover.
But, nothing to worry if you're not able to tackle it now. We can get it done in the next iteration. 

I'll take a look at the PR and leave my comments!

**Comment by eswarasai** [comment]
@CosmicCoder96 -- We've decided to take care of this internally due to the urgency on this feature getting shipped out. I'll let @pelsasser tip you for your efforts and contribution. Thanks!

**Pull request closed without merging**
