### PR TITLE
Initial commit for removing hard-coded gas limit

### PR DESCRIPTION
**Pull request by eswarasai**
##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes: #132

### CODE REVIEW

**Comment by eswarasai** [comment]
@pelsasser -- I too had similar concern with Metamask. Wanted to hide the `Gas Limit` field in case of Metamask but left it as it is thinking we might actually end up with a logic to estimateGas like suggested above in which case it makes sense to have it disabled. In case of `truffle`, I've given the flexibility for user to modify the `Gas Limit`, i.e., it isn't disabled in this scenario.

I'm not sure on how to implement `estimateGas` as it needs `data` param, which might be difficult to handle in case of the `QuickDeploy`. If you have any idea here, I can go ahead and implement it, if not, I'll hide the `Gas Limit` input for `Metamask` scenario and update the PR. Let me know what you'd suggest. Thanks!

**Comment by pelsasser** [comment]
Okay - reminded me of this  - 

https://ethereum.stackexchange.com/questions/11053/how-to-estimate-gas-at-contract-creation-deployment-to-private-ethereum-blockcha?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

I think we should be able to get pretty close without even considering the actual data a user is entering (IE using default / dummy values).

I can try and get to this to see if I am able to find a solution in the coming days if you aren't sure about figuring out the estimate.   LMK how you want to proceed.

**Comment by eswarasai** [comment]
@pelsasser -- Thanks for that. I'll try to get this working and update the PR in the next couple of days. Will reach out to you in case I've any concerns :)

**Comment by pelsasser** [comment]
see #161 for some more color.

**Pull request merged**
