### PR TITLE
Added WelcomeMessage component and tests for that accordingly

### PR DESCRIPTION
**Pull request by vikaskyadav**
##### Description
Welcome Modal will appear as a result of this once the user comes on the landing page. This is a newly created PR which serves as an alternate for the old one for WelcomeMessage. I hope we will be able to move this in forward direction. @eswarasai  @pelsasser  need you people in this.

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
UI

##### Refers/Fixes
Fixes: #120

### CODE REVIEW

**Comment by pelsasser** [comment]
@eswarasai - I spoke with @vikaskyadav yesterday and he asked that either you work on this, or we open it up to other bounty hunters to finish.  LMK how you want to proceed, happy for either approach.

**Comment by eswarasai** [comment]
@vikaskyadav -- Thanks for the requested changes in the PR. I'll be taking it forward from here.

**Comment by eswarasai** [comment]
@vikaskyadav -- Right now the behaviour is that, whenever user loads `dApp`, on the landing page we display the welcome message, even on page refresh we're displaying that message because we want to notify the user about the instructions. Both `Cancel` and `Proceed to dApp` are performing same actions right now but down the line we'd change this behaviour.

@pelsasser -- I've fixed the functionality of WelcomeMessage component to above intended behaviour as well as added tests to increase the coverage. Feel free to review and merge the PR.

**Comment by pelsasser** [comment]
@vikaskyadav @eswarasai - this looks good to merge.  I will work on the copy for it after we merge.

I would recommend we remove the `cancel` button since it provides no functionality

There are a few more features we can add to this as well.  Once merged and I have worked on the text, header, etc. We can then create those issues as well.

**Comment by vikaskyadav** [comment]
Sounds good. We can make changes iteratively on this.

**Pull request merged**
