### PR TITLE
Added a route in App.js to its Router component.

### PR DESCRIPTION
**Pull request by nithinr07**
##### Description
React Router redirects `/exchange/*` routes back to `/exchange`

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes: #312

### CODE REVIEW

**Comment by nithinr07** [comment]
Can someone let me know why the travis-ci build failed? I am not able to figure out what went wrong. Thanks!

**Comment by eswarasai** [comment]
@nithinr07 -- Looks like there's a failing test in `App.test.js` due to the code changes I guess. Please take a look at it and fix them. Thanks!

**Comment by nemaniarjun** [comment]
Hey @nithinr07 I have a better solution over at this PR https://github.com/MARKETProtocol/dApp/pull/326. The way I have done it will make sure that in future, we can add more reroutes easily and simply. The PR is not completely tested and was just from the top of my head idea of how we should go about it. :grin:

@eswarasai Do check out the aforementioned PR. :)

**Comment by nithinr07** [comment]
@nemaniarjun I am fairly new to React, well, anyway, whatever is the best approach! Let me know what I can do! :)

**Comment by nithinr07** [comment]
@nemaniarjun So, what else is left to be done?

**Comment by nemaniarjun** [comment]
Checkout my PR, I think it is ready to be merged. 
CC @eswarasai :grinning:

**Comment by nithinr07** [comment]
@nemaniarjun Shall I update my PR to your approach so that we pass Travis?

**Comment by nithinr07** [comment]
Acknowledgements : @nemaniarjun 
@eswarasai I guess this issue can be closed now. Do let us know if something needs to be changed!

**Pull request merged**
