### PR TITLE
Remove pre-funding needs

### PR DESCRIPTION
**Pull request by pelsasser**
Currently the first query from oraclize.it is free - we can right now get away with not paying anything into the contract to start.

### CODE REVIEW

**Comment by eswarasai** [comment]
@pelsasser -- I'm a little confused here w.r.t. the changes. So, Deploy Contract works for the first time since the first query from oraclize.it is free but the next one would fail, is that correct? Or have I misunderstood something here?

**Comment by pelsasser** [comment]
yea - there is some weird behavior going on, so lets hold off on merging this

**Comment by eswarasai** [comment]
@pelsasser -- Is this needed or would @cryptomental changes be a better way to tackle this scenario?

**Comment by pelsasser** [comment]
Okay - so builds are passing now.  I think we should think about merging this.  

We can save #37  for when we change the protocol - but for now the contract creator doesn't need to pay anything in regards to the first query - it is free with oraclize.it

**Pull request merged**
