### PR TITLE
Truncating 'Available to Deposit' amount to 2 decimal digits in wallet section of Sim exchange

### LINKED ISSUE #310: [UI/UX] Handle long numerical digits in Sim exchange wallet
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Wallet amount which exceeds certain decimal digits is looking weird right now. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: UI Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
walletdatatolong

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Fix the current behavior by figuring out a proper solution to it.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Long wallet amount should not break to next line

### PR DESCRIPTION
**Pull request by nitinrgupta**
##### Description

Truncating 'Available to Deposit' amount to 2 decimal digits. 

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)

UI

##### Screenshots (Optional) 

screen shot 2018-08-29 at 5 50 04 pm

##### Testing

Tested briefly

##### Refers/Fixes

Fixes #310

### CODE REVIEW

**Comment by travisdmathis** [comment]
@nitinrgupta shouldn't round up should just truncate. They don't actually have 14.05 and i predict someone trying to put in .05 when they really have .049999999998 doh

**Comment by nitinrgupta** [comment]
@travisdmathis Ah! You're right. You suggested rounding off in the issue thread which influenced the decision of me rounding off 😅

**Comment by nitinrgupta** [comment]
@travisdmathis hahaha no worries. Pushed the changes. Please have a look!

**Comment by nitinrgupta** [comment]
@travisdmathis any other changes which you notice to be done?

**Pull request merged**
