### PR TITLE
adding build files from deployment to rinkeby

### PR DESCRIPTION
**Pull request by pelsasser**
This will allow devs to interact with the deployed contracts to rinkeby without having to deploy themselves.

### CODE REVIEW

**Comment by eswarasai** [comment]
@pelsasser -- I wouldn't really recommend this way of having the contracts as part of the repository and use it in order to get the dApp connected to Rinkeby testnet working. I think it'd be better if we can provide the steps for the Dev to deploy the contracts to either `truffle`/`Rinkeby` as per their needs. Let me know your thoughts on this. Thanks.

**Comment by pelsasser** [comment]
@eswarasai - it is expensive time wise and pretty redundant to do so.  It probably takes ~10 minutes for all the contracts to deploy in sequential fashion due to block times. Not to mention syncing a local node which can take a while depending on connection speeds.

With the ABI's included, all a dev would need to do to connect to rinkeby would be `npm run start` and use a metamask enabled browser pointed to rinkeby.  

Dev process without ABI's

1.  Get test ether into a wallet from a faucet
2.  Run a light geth node, connected to rinkeby and provide access to the unlocked wallet
3.  After syncing all the needed blocks, run truffle migrate --network rinkeby
4.  Wait ~10 minutes for deployment
5.  `npm run start`

Dev Process w/ ABIs
1. `npm run start`

What is the downside of adding the ABIs?  The obvious ones I see are that we have to update them whenever we update `market-solidity`

**Comment by eswarasai** [comment]
@pelsasser -- Understood. For Dev/Tests purposes, I don't think there's much usage for Rinkeby network. I'm pretty sure it'd be just you and me ending up using Rinkeby network. Moreover we'd be encouraging them to use local truffle/ganache for the Dev purpose and also would have a Docker env setup in a similar manner.

Another reason I wouldn't suggest adding `build` folder to the repo is that, if I run `truffle migrate` using local `ganache`, I need to be very careful to not commit those files all the time as well as need to watch out for the same in each and every PR. I'm sure it'd be frustrating for the Devs to take care of it as well.

I understand that deploying contracts to Rinkeby is a bit time consuming as well requires extra efforts but we'll let the Dev decide whether he wants to use the local truffle/ganache or Rinkeby testnet and provide instructions to do so for the same. Makes sense?

**Comment by pelsasser** [comment]
`./build` is still covered under `.gitignore` so there wouldn't be any commits unless forced their addition of their updates ABI's after locally deploying to a test net.  

We can put them somewhere else as well, perhaps in another folder or another repo. I personally would like them somewhere publicly accessible for when people need to work on the dApp with items or issues that are only seen in public test nets as we enter a public beta.

**Comment by pelsasser** [comment]
alright - we have best of both worlds now.  

`make start_dapp_rinkeby`

is now all that is required to run the dApp locally connected to rinkeby.

**Comment by pelsasser** [comment]
hat tip to @pchuck for the Makefile

**Pull request merged**
