### PR TITLE
Extend simplified deployment to allow for assets denominated in USDT

### PR DESCRIPTION
**Pull request by dilatebrave**
##### Description
- [x] Change filter in ExchangeSource.js to also incorporate USDT as a quote asset.
- [x] Change collateralToken from WETH to deployed fake stablecoin
- [x] Update copy around ETH based pairs in this step

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
SimplifiedDeployment

##### Testing
Local

##### Refers/Fixes
Fixes: #188

### CODE REVIEW

**Comment by pelsasser** [comment]
@dilatebrave thanks! looks like @eswarasai will do a review, but really appreciate the PR

**Comment by eswarasai** [comment]
@dilatebrave -- Everything looks good to me except for the part of selecting the `ETH`/`USD` symbol pairs. Is it possible to provide auto-complete with grouping similar to what Ant Design provides here -- https://ant.design/components/auto-complete/#components-auto-complete-demo-certain-category?

**Comment by dilatebrave** [comment]
@eswarasai -- i've added select group and filter

**Comment by eswarasai** [comment]
@pelsasser -- I'm planning to merge this now. Anything you might wanna add here w.r.t. functionality?

**Pull request merged**
