### PR TITLE
Feature/37 deployer calculate estimated cost

### PR DESCRIPTION
**Pull request by cryptomental**
This solves #37 . It took me a lot of time and I again learnt a lot.

The last thing are automatic tests but this will need to be a part of #61 as we need to figure out how to properly mock and test redux actions.

I executed manual tests using QuickDeployer and everything works as expected.

The easiest way to see it in action is to start truffle, bridge, app, make sure that explorer shows initial contracts and visit:

http://localhost:3000/contract/deploy?mode=quick&contractName=BTCUSD&priceFloor=70000&priceCap=100000&priceDecimalPlaces=1&qtyMultiplier=1&oracleDataSource=URL&oracleQueryRepeatSeconds=60&baseTokenAddress=0xaa588d3737b611bafd7bd713445b314bd453a5c8&oracleQuery=json(https://api.gdax.com/products/BTC-USD/ticker).price

I noticed that baseTokenAddress is quite deterministic when I start truffle development network.
This URL will pre-populate QuickDeployer to schedule queries once a minute and use a contract BTC-USD between 7-10K USD which is still valid when I am writing this.

I am pasting below a set of screenshots that show how the contract was executed, the price was updated using Oraclize callback values and how the contract is settled with the final price, which is visible both in the 'bridge' console of IDE and in the web UI, which is a good showcase of the dApp:

screenshot from 2018-03-17 17 58 26

screenshot from 2018-03-17 18 01 15

screenshot from 2018-03-17 18 02 08

screenshot from 2018-03-17 18 02 29

screenshot from 2018-03-17 18 03 31

screenshot from 2018-03-17 18 04 31

screenshot from 2018-03-17 18 04 52

screenshot from 2018-03-17 18 05 51

@pelsasser @eswarasai @perfectmak I rebased the branch against current master. The PR can be merged as-is if it is ok.  I left out a few debug logs on the console, they can be removed before merging or later if needed.

### CODE REVIEW

**Comment by cryptomental** [comment]
I added protection for isNaN similar to other fields and added mocked preFunding value in DeployContrac test to make sure that all tests pass.

**Comment by pelsasser** [comment]
Just going through this now.  Seeing a few issues 

**If a short duration is selected for the expiration, and a longer period for frequency, no pre-funding is suggested**
image

It also may be better to tell people what units we are displaying this in!  Unitless values can be quite scary.  Perhaps a dropdown could allow people so select their desired units (wei, gwei, eth, etc)

We also need to integrate the same functionality into the guided contract deployer with more explanation as the values and how we arrive at them.  

We can keep in mind that we are moving away from [recursive queries](https://github.com/MARKETProtocol/MARKETProtocol/issues/57) so the math should be a little easier to figure this all out. 

haven't look at any code yet - maybe @eswarasai can dive into the code

**Comment by cryptomental** [comment]
Hi @pelsasser Thank you for the feedback. I like the idea of the dropdown to select the unit. I will also remove the debug logs.

**Comment by cryptomental** [comment]
I am closing this PR and will reopen it once ready for another round of the review.

**Pull request closed without merging**
