### PR TITLE
API for contract whitelist

### PR DESCRIPTION
**Pull request by StevenJNPearce**
##### Description
see https://github.com/MARKETProtocol/dApp/issues/87

##### Affected core subsystem(s)
No

##### Testing
Tested enpoints with curl. Let me know if you want me to write formal tests with mocha + chai.

### CODE REVIEW

**Comment by pelsasser** [comment]
@StevenJNPearce - I am hoping @eswarasai can provide a review of this ASAP, but yes we definitely would appreciate "formal" tests written as well.

**Comment by pchuck** [comment]
@eswarasai i created a branch based on this PR and added a makefile to make it easier to provision the services, deploy and test the code

**Comment by pelsasser** [comment]
@StevenJNPearce just to keep you in the loop we are internally going through the needed set up here to test out the deployment. We are also discussing creating a seperate repo for the serverless infra.

Once we can confirm this is working will update the comments here. Definitely would appreciate the testing you mentioned as well.

**Comment by pelsasser** [comment]
@StevenJNPearce - maybe you can assist a bit - currently deployed to
 https://560txmy2e6.execute-api.us-east-1.amazonaws.com/dev/whitelist without success as you can see. can you help me troubleshoot? maybe connect in marketprotocol.io/discord ?

**Comment by pelsasser** [comment]
@StevenJNPearce - thanks so much for helping with the deployment!

  We have discussed internally and are goingto create a new repo for the backend framework [here](https://github.com/MARKETProtocol/backend)

I was hoping you would be willing to help us with setting up 

1. Testing 
2. CI 
3. Integrating the changes made here into the dApp function calls to interact with serverless as discussed in #87

We would love to close this PR - pay out the bounty, and move the rest of this to the new repo and get you some more ETH to help with the remaining tasks.

**Pull request closed without merging**
