### PR TITLE
Add mobile nav

### PR DESCRIPTION
**Pull request by KennethAshley**
##### Description
This PR aims to add mobile nav

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Affected core subsystem(s)
UI, UX

##### Refers/Fixes
Fixes: #194

### CODE REVIEW

**Comment by pelsasser** [comment]
@KennethAshley - looks like there are some issues with the build? Can you resolve so we can get this merged?

**Comment by eswarasai** [comment]
@KennethAshley -- Also while you're at it, please do rebase with `upstream:develop` and resolve the conflicts. Thanks!

**Comment by eswarasai** [comment]
@KennethAshley -- Any update here? Also what are the pending things here since the PR is still a WIP?

**Comment by KennethAshley** [comment]
@pelsasser back in civilization (went to the mountains) i'll knock this out today.

**Comment by KennethAshley** [comment]
@eswarasai can you take a look at the Travis CI build? not sure why its failing

**Comment by eswarasai** [comment]
@KennethAshley -- I'm looking into it. It's because of the version upgradations in the `package.json`, especially for `rxjs` which is a dependency for `lint-staged`. I'll take care of it in your branch. Are you completely dev done on this and the PR is ready for review?

**Comment by KennethAshley** [comment]
@eswarasai yea! it should be good for review!

**Pull request merged**
