### PR TITLE
Initial commit for standardizing contract name

### PR DESCRIPTION
**Pull request by eswarasai**
##### Description
- Removed Quick and Guided Deploy flow from Navbar
- Added `Contract Name` step to add user input text

##### Checklist
- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Refers/Fixes
Fixes: #270 

##### TODO
- [ ] Fix UI input for the Contract Name
- [x] Fix failing tests

### CODE REVIEW

**Comment by pelsasser** [comment]
@eswarasai - I think it is looking pretty good with a few comments.

image



1.  `REFERENCEASSET_COLLATERALSYMBOL_DATAPROVIDER_EXPIRATION_USERTEXT` is the intended format, So in the case displayed above it would be `BTC_USDT_BIN_15777..._ ` If it is too hard to programmatically and reliably across all these APIs pull out BTC, I think `BTCUSDT_USDT_BIN_15777..._ ` would be fine as well.
1. It looks like you have tapped @nitinrgupta for the UI piece, only comment I really have there is making it clear to the user there is a standardized naming schema, and a free for portion, they can use if they want. 
1. Otherwise LGTM

**Comment by eswarasai** [comment]
@pelsasser -- My bad. I've reversed the symbols now. I can do the parsing for removal of `USDT` from `BTCUSDT`. So currently we have `symbolName` which is `BTCUSDT` and `quoteAsset` which is `USDT`. If the `quoteAsset` i.e., `ETH`/`USDT` are always part of `symbolName`, I can handle the additional parsing if the above logic is always valid. Please do confirm once.

@nitinrgupta -- I'm awaiting on your commit to fix the UI as well as handling Phil's comment. Thanks!

**Comment by nitinrgupta** [comment]
@eswarasai @pelsasser what do you guys think? The copy can be modified 😉 

Initial - 
screen shot 2018-08-28 at 5 15 35 pm

Once the user enters the custom name
screen shot 2018-08-28 at 5 15 20 pm

**Comment by eswarasai** [comment]
@nitinrgupta -- Not sure if the `userText` in the contract name is optional. @pelsasser can you confirm the same because the parsing functions assume it's mandatory in the `MARKET.js`?

**Comment by nitinrgupta** [comment]
@eswarasai Oh! allright then. We can remove that `Optional` helptext

**Comment by pelsasser** [comment]
```
  parseStandardizedContractName(contractName: string): ParsedContractName | null {
    let splitName: string[] = contractName.split('_');
    if (splitName.length < 4) {
      return null;
    }

    let expiration;
    try {
      expiration = new BigNumber(splitName[3]);
    } catch (err) {
      return null;
    }

    return {
      referenceAsset: splitName[0],
      collateralToken: splitName[1],
      dataProvider: splitName[2],
      expirationTimeStamp: expiration,
      userText: splitName.length > 4 ? splitName[4] : '' // user text could be optional
    };
  },
```

Currently in parsing it's optional, but @eswarasai is correct in the `createStandardizedContractName` I didn't make the function as flexible.  Maybe we do want it optional, what do you guys think?

**Comment by nitinrgupta** [comment]
I'm open to make it optional

**Comment by eswarasai** [comment]
@pelsasser -- I'm not really sure about the business requirement here but it'd be easier if we have `userText` as mandatory in order for me to quickly search through the contracts in the Explorer UI. I'll leave it upto the team to decide what's better.

cc: @MARKETProtocol/core

**Comment by pelsasser** [comment]
@eswarasai - okay, we can leave it as mandatory, no problem.

**Comment by eswarasai** [comment]
@nitinrgupta -- Can you paste the CSS for the `Final Contract Name` value here?

**Comment by nitinrgupta** [comment]
@eswarasai here's the zeplin link : https://app.zeplin.io/project/5b06ec51910686b53d883851/screen/5b86c5f8b2dafb0b1d21ac99

**Comment by eswarasai** [comment]
@pelsasser -- This is good to be reviewed and merged except for one minor UI change that needs to be reviewed by @nitinrgupta as per above comment.

Weird that though coveralls percentage is decreased, it's giving green status. I've observed the same behaviour in couple of other PRs as well. Not sure what's up with coveralls.

**Comment by nitinrgupta** [comment]
@eswarasai `font-size` 10 should be fine considering the long name we're planning to house in single line. But if you're feeling the other way then go ahead and make it `12px` :)

Also, opacity should be `0.7`. Updated the zeplin with the same

**Comment by eswarasai** [comment]
@nitinrgupta -- Cool. I'm leaving `font-size` as `12px` and `opacity` at `0.7`. Yeah, we cannot help with the line break due to the container padding. It should be fine I guess.

@pelsasser -- All set for merging 👍 Let me know if you have any other feedback that's needed to be taken care of. Thanks!

**Comment by pelsasser** [comment]
@eswarasai @nitinrgupta - everything looks good here.  

Do you think we should change the copy from `Set Contract Name` to something like `Add custom text to contract name` ?

Not sure it matters, but you get the idea

**Comment by eswarasai** [comment]
@pelsasser -- Is this good to be merged or anything else is pending?

**Pull request merged**
