### PR TITLE
ISSUE #71 PR

### PR DESCRIPTION
**Pull request by maektwain**
As per the requirement of the issue stated.

Let me know the feedback.

Thanks

### CODE REVIEW

**Comment by cryptomental** [comment]
Hi @maektwain , you can also remove line https://github.com/maektwain/Dapp/blob/2132a9eb8a86b2a5a5ee8c1bd263d6e6643256c4/src/actions/explorer.js#L58 as it is not used anymore.

**Comment by cryptomental** [comment]
Btw. this PR only solves the issue partially. The main point was to enable any ERC20 token to be displayed.

**Comment by maektwain** [comment]
Hey @cryptomental is this right approach 

``
const token = contract(abi).at(baseTokenContractAddress);
            contractJSON['BASE_TOKEN'] = token.name();
            contractJSON['BASE_TOKEN_SYMBOL'] = token.symbol();
``

**Comment by cryptomental** [comment]
@maektwain you may want to try to deploy a 'Hamburger' token in the development network and see if that works http://www.masonforest.com/blockchain/ethereum/2017/11/13/how-to-deploy-an-erc20-token-in-20-minutes.html

and then quick'n'dirty https://stackoverflow.com/questions/45364197/how-to-detect-if-an-ethereum-address-is-an-erc20-token-contract

**Comment by maektwain** [comment]
@cryptomental  Thanks for providing the direction. One more thing is it necessary to check the validity of ERC20 contract.  Yeah I think If it is, this is really the right way to do it.

**Comment by cryptomental** [comment]
@maektwain yes, I think this is the way to do it. I think the checks mentioned in the stackoverflow answer above will be sufficient.

**Comment by maektwain** [comment]
Hey, @cryptomental I have moved this PR to #73 .

**Pull request closed without merging**
