### PR TITLE
TimePicker Several bugs with selecting times for expiration

### PR DESCRIPTION
**Pull request by octavioamu**
##### Description

- [x] Fix Time Picker to allow users to pick a time for expiration
- [x]  Remove the Now button since who wants to have a contract immediately expire
- [x]  Make timezone explicit and ensure it lines up with how we are creating the contracts with a UTC timestamp
- [x]  update and add tests to ensure timezone are handled appropriately translating into a correct UTC timestamp for contract creation.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)

UI, UX, Tests

##### Screenshots (Optional) 

**BEFORE**

image

**AFTER**

image

image

##### Testing

I had tested with rinkeby and also made some visual changes for text with low contrast  (unreadable) and made some research for the UX decision.  

##### Refers/Fixes

Fixes: #213

### CODE REVIEW

**Comment by eswarasai** [comment]
@octavioamu -- This is all looking good to me. I just have couple of styling updates needed to merge the PR --

- Center align the current date in the square box
```
.ant-calendar-date {
    padding-left: 2px;
}
```

- Increase the width of the calendar to fit the selected date and time along with the GMT to avoid `overflow-x`
```
.ant-calendar {
    width: 300px;
}
```

**Comment by octavioamu** [comment]
@eswarasai Perfect! I will update it now

**Comment by octavioamu** [comment]
@eswarasai padding-left: 2px; is actually uncentering the content 2 px to left
image

**Comment by octavioamu** [comment]
I think I get why you suggested that padding, should be for the lined box of "today" but the problem is that affected all the dates. The solution was to change a little how ant-date made the css and now that box adapts well to any size of calendar.
Example: 
image

**Pull request merged**
