### PR TITLE
changes color of link

### PR DESCRIPTION
**Pull request by I3uckwheat**
### Description
Makes it easier to read links in message boxes

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
UI, UX

##### Screenshots (Optional) 
Old:
old setting
New:
image

##### Refers/Fixes
Fixes: #127

### CODE REVIEW

**Comment by eswarasai** [comment]
@I3uckwheat -- The text doesn't look like it's clickable in the `message`. It's blending with the color of the actual text. Please refer to the screenshot below:

screen shot 2018-06-01 at 6 27 16 pm

And also please do rebase your branch with that of the latest `upstream/develop`. Thanks!

**Comment by I3uckwheat** [comment]
image

I have lightened the color a bit more, is this ok?

**Comment by eswarasai** [comment]
@I3uckwheat -- I'm unable to tell it from the screenshot. Can you please comment on PR with the list of color codes that you think might be better for link text, so that I can try it out on my end and approve the one that's looking good? Thanks!

**Comment by I3uckwheat** [comment]
@eswarasai 
#009c80
#00a285

Another option to make it look more clickable is adding an underline, but i'm unsure if that follows the guidelines though.

Another solution i have been playing with is adding a slight drop-shadow
```
#market .ant-message a {
  color: #00c3a0;
  text-shadow: 0px 0px 1px #009c91b8;
}
```
That looks like this

image

**Comment by pelsasser** [comment]
@eswarasai - bump

**Comment by I3uckwheat** [comment]
@eswarasai Looks good to me, i just submitted a PR

**Pull request merged**
