### PR TITLE
[Simplified Deploy Contract] Updated Price Floor and Price Cap

### PR DESCRIPTION
**Pull request by pfilippi24**
##### Description

- [x] Hide the Price Qty Multiplier input field in Step 2 of Simplified Deploy Contract
- [x] Display current price of the selected symbol
- [x] Allow user to use decimal places for price floor and price cap
- [x] Fix the test cases, if at all broken and also ensure that the coverage hasn't decreased

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

##### Affected core subsystem(s)
UI

##### Testing
Manual tests only so far, but still work in progress

##### Refers/Fixes
Fixes: #164

### CODE REVIEW

**Comment by eswarasai** [comment]
@pfilippi24 -- LGTM. Only change would be to update the current price to simple text instead of having a disabled input. And also please do try to increase the coverage. Thanks!

**Comment by pfilippi24** [comment]
@eswarasai 
Current price is now simple text. Kept it as hidden input though for easier validation.
Test coverage isn't decreased anymore (went up by 0.2%)

**Comment by eswarasai** [comment]
@pfilippi24 -- Could you please squash all your commits into single one? Thanks!

**Comment by pfilippi24** [comment]
@eswarasai done

**Pull request merged**
