### PR TITLE
adds test query gas estimate re: #132

### PR DESCRIPTION
**Pull request by pelsasser**
Did a bunch of digging into estimate the gas amounts for deployment.

https://github.com/trufflesuite/truffle-contract/tree/web3-one-readme

truffle-contract is being upgraded to handle `new.estimateGas` and a few other cool functions that we should probably just wait for.  However I did provide an example of implementing a solution for estimating the queryTest gas.  We need to extend this to be reflected in the user form, but this currently works for the transaction itself. 

##### Checklist
- [x] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Refers/Fixes
Refs: #132
Refs: #158

### CODE REVIEW

**Comment by pelsasser** [comment]
Tests fail on this as well - simply meant to be an example no need to merge.

**Comment by eswarasai** [comment]
@pelsasser -- The problem with this approach is, even if we get the `estimateGas`, it's not being shown to the user while actually modifying the inputs. The only approach we can take is to have dummy values and `estimateGas` on page load. Makes sense?

**Comment by pelsasser** [comment]
@eswarasai - yup - I think dummy values plus a buffer will work well.

**Comment by eswarasai** [comment]
Cool. I'll update the PR #158 accordingly 👍

**Pull request closed without merging**
