### PR TITLE
Modularly import antd components and styles

### LINKED ISSUE #172: [packages] antd import issues
### Description

Should we optimize bundle size more carefully?

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug?

### Current Behavior
[comment]: # (Describe what actually happened.)
Console warning re:

>       You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

### PR DESCRIPTION
**Pull request by arun1595**
##### Description

Import antd components and styles modularly.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Testing

Tested.

##### Refers/Fixes

Fixes #172

### CODE REVIEW

**Comment by eswarasai** [comment]
@arun1595 -- The PR looks good to me but have we done this change in order not to have those console warnings during the tests or is the `babel-plugin-import` isn't actually optimizing the `antd` imports in dev/prod builds?

**Comment by eswarasai** [comment]
@arun1595 -- Can you please clarify my above question?

**Comment by arun1595** [comment]
@eswarasai I am a bit confused as well. I'll get back to you after analyzing the bundle.

**Comment by eswarasai** [comment]
@arun1595 -- Sure. Thanks. If the console warning is just popping up during tests and not with the production build, it should be fine I guess. Every time importing component and style separate from `antd` isn't suggestible.

**Comment by eswarasai** [comment]
@arun1595 -- Any update on this one?

**Comment by arun1595** [comment]
@eswarasai Ah, missed this. Will get back to you soon with an update.

**Comment by eswarasai** [comment]
@arun1595 -- Were you able to spend some time on this or should I close the PR in favour of ignoring the console warnings during the tests?

**Comment by arun1595** [comment]
@eswarasai I spent a bit of time on it but couldn't really understand what's going on. I was fetching the module and styles separately from reading the examples in the [documentation](https://github.com/ant-design/babel-plugin-import#example)

Looks like there's some magic happening during the build which modularly imports the `antd` components which is nice as we don't have to import every component and style separately but I don't have a clear understanding of it though.

I think something else is wrong which is why the console warnings are displayed during the test. I'm closing this for now, will reopen if necessary.

**Pull request closed without merging**
