### PR TITLE
Added WelcomeMessage component and content inside this along with Metamask logo.

### PR DESCRIPTION
**Pull request by vikaskyadav**
Added WelcomeMessage component and content inside this along with Metamask logo.

##### Description
Welcome Message works as the user comes on LandingPage. Need feedback from people and @pelsasser will be updating the message/ Instructions inside the popup.

##### Checklist
- [ ] Linter status: 100% pass
- [ ] Changes don't break existing behavior
- [ ] Tests coverage hasn't decreased

##### Affected core subsystem(s)
UI

##### Refers/Fixes
Fixes: #120

### CODE REVIEW

**Comment by eswarasai** [comment]
@vikaskyadav -- Sorry for the delay in getting back. I'll try to get this merged between today and tomorrow. Thanks for your work :)

**Comment by vikaskyadav** [comment]
Yeah @eswarasai  let me know if there is some issue with this PR.

**Comment by eswarasai** [comment]
@vikaskyadav -- Please find the below issues with the PR

- The Welcome Message should ideally come only once when the User is visiting the Landing page. If I navigate to some other page and come back to Landing page via clicking on the MARKET Protocol logo in the Navbar, the Welcome Message shouldn't be popping up again
- Please add the necessary tests for the added component to increase the coverage. As you can the coverage has been decreased
- Please fix the `eslint` warnings related to the WelcomeMessage component

@pelsasser -- Let us know if the test of the Welcome Message component needs to be updated. You can checkout the existing one in the below screenshot. And also I feel there's no need for `Cancel` button here as there's no such action. I'd recommend just to keep the `Proceed to dApp` button in the Modal

screen shot 2018-05-03 at 5 12 48 pm

**Comment by vikaskyadav** [comment]
@eswarasai  We can keep some flag to check for the condition whether the user came on landing page for the first time. As soon the user visits the page, we toggle this flag and display the Modal based on this condition. Let me know how you can help me close this asap.

**Comment by eswarasai** [comment]
@vikaskyadav -- Sure. The flag implementation sounds good to me. Let me know if you need any help in specific. Feel free to join the [Discord](https://marketprotocol.io/discord) channel. Thanks :)

**Comment by pelsasser** [comment]
@vikaskyadav @eswarasai thanks for going through this together. Once we merge, I will spend some time updated the text of the welcome message itself.  I think the structure works for what we are trying to achieve and I can refine the bullets. thanks @vikaskyadav this will be really nice for first time users of the dApp

**Comment by vikaskyadav** [comment]
Sound cool.  I will do the required changes very soon.

**Comment by vikaskyadav** [comment]
@eswarasai  using the state variable won't work. I have two other ways to do this: either we save it in store or we use the localStorage. Let me know which one will be good to use.

**Comment by vikaskyadav** [comment]
@eswarasai I need to close this issue asap. need your help. I have to take up other issues too after this.

**Comment by eswarasai** [comment]
@vikaskyadav -- Sorry about the delay in getting back to you earlier. So you can keep a state variable on the parent component where the `WelcomeMessage` is being rendered and pass the `visibility` as a `prop` along with the function to update the parent component `state` variable to be updated to `false`. And also please add the necessary test cases to increase the coverage without which we wouldn't be able to get this merged. Thanks!

**Comment by eswarasai** [comment]
@vikaskyadav -- Any update here? Let me know if you want me to handle this for you so that I can get this PR merged quickly and have you paid out. Thanks!

**Comment by vikaskyadav** [comment]
I need a little help writing tests. Not that much familiar with chai.
Otherwise, it's done I guess. give me sometimes and i'll let you know.

**Comment by pelsasser** [comment]
@jintoppy  is a test master, he may be willing to help

**Comment by jintoppy** [comment]
@vikaskyadav let me know if I can be of any help

**Comment by eswarasai** [comment]
> Using the state variable won't work. I have two other ways to do this: either we save it in store or we use the localStorage

@vikaskyadav -- I thought this was still pending. Can you confirm on that? If it's just coverage of unit tests pending, let us know so that I can quickly update them. Thanks!

**Comment by vikaskyadav** [comment]
ok. I need somebody's help here. I wanted to use some flag to check if Modal has come up once. I wanted it to keep it simple, that's why didn't bother to store it in store. Kept a check in the parent component of WelcomeMessage which is Landing.js but I need to track the state even after component gets unmounted. Plus, there is one more way to use localStorage but it's not a good approach to do that. If somebody can help me out, please do let me know.

**Comment by vikaskyadav** [comment]
I think forcefully pushed after revising history and github hook closed it.

**Pull request closed without merging**
