### PR TITLE
Feature/my fills executions

### PR DESCRIPTION
**Pull request by travisdmathis**
##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased

### CODE REVIEW

**Comment by eswarasai** [comment]
@travisdmathis -- This is looking good to me. I'll let @nitinrgupta give the final approval and merge this one 👍

**Comment by nitinrgupta** [comment]
@travisdmathis this change gives the data which eventually replaces the temp fill text area and submit button we have currently right?

**Comment by travisdmathis** [comment]
@nitinrgupta correct, i left the fill stuff for now so we can use it until we have the new widget.

**Comment by nitinrgupta** [comment]
@travisdmathis I'll leave the issue open since we haven't done the displaying fills in the UI as it describes part.

**Pull request merged**
